### ISSUE TITLE
why i can't play 4k in edge

### ISSUE THREAD

**Issue by hihaozhe** [lkmvip/netflix-4K-DDplus#11]
why i can't play 4k in edge

**Comment by lkmvip** [comment]
https://help.netflix.com/zh-tw/node/13444

**Comment by hihaozhe** [comment]
![image](https://user-images.githubusercontent.com/63550512/98059446-22998400-1e82-11eb-821f-440778f40166.png)

**Comment by Phoenomenal** [comment]
hihaozhe  were you able to play 4k in new edge at least a week ago ?  

For me it was working fine until about october 29 when suddenly video quality became 1080p  at max (no hevc,  prk,  hdr  in video codec only avc/avchigh)   Netflix  win 10 app works ok and i cant watch 4k + hdr using it.  

There is even a thread in reddit about it 
 https://www.reddit.com/r/MicrosoftEdge/comments/jkh7y6/netflix_4k_is_not_working_on_new_edge_but_it/

So its a common problem i guess.   The best way to watch 4k on pc right now  (and hdr if you have capable monitor)  is to use Netflix app

**Comment by lkmvip** [comment]
> hihaozhe  were you able to play 4k in new edge at least a week ago ?  
> 
> 
> 
> For me it was working fine until about october 29 when suddenly video quality became 1080p  at max (no hevc,  prk,  hdr  in video codec only avc/avchigh)   Netflix  win 10 app works fine and i can watch 4k + hdr using it.   
> 
> 
> 
> There is even a thread in reddit about it 
> 
>  https://www.reddit.com/r/MicrosoftEdge/comments/jkh7y6/netflix_4k_is_not_working_on_new_edge_but_it/
> 
> 
> 
> So its a common problem i guess.   The best way to watch 4k on pc right now  (and hdr if you have capable monitor)  is to use Netflix app 

now i fixed this problem

https://github.com/lkmvip/netflix-4K-DDplus/commit/7c3ec792f9b15bebccff570c0efd5dda0bf9fa97

**Comment by Phoenomenal** [comment]
lkmvip,   Thanks.  4K + HDR works  now in Microsoft Edge  after i edit cadmium-playercore-6.0026.529.031.js  file like in your post .

**Comment by 5J2J** [comment]
Forgive my ignorance, where do I do this?

**Comment by Phoenomenal** [comment]
5J2J ,  you can simply drop this edited file https://www.mediafire.com/file/l2l1k3cpxdvzh3y/cadmium-playercore-6.0026.371.031.js/file   in  your netflix-4K-DDplus extension root folder rewriting your cadmium-playercore-6.0026.529.031.js file

**Comment by hihaozhe** [comment]
![image](https://user-images.githubusercontent.com/63550512/98183188-9f8c3280-1f42-11eb-8956-0019d328c8da.png)
after install Microsoft Store link，i can play videos ，but I still can't play 4K

**Comment by lkmvip** [comment]
> ![image](https://user-images.githubusercontent.com/63550512/98183188-9f8c3280-1f42-11eb-8956-0019d328c8da.png)
> after install Microsoft Store link，i can play videos ，but I still can't play 4K

Recommended software:
1,Win10.Ver.2004

**Comment by lkmvip** [comment]
> Forgive my ignorance, where do I do this?

https://github.com/lkmvip/netflix-4K-DDplus/archive/master.zip

**Comment by 5J2J** [comment]
Edge
![image](https://user-images.githubusercontent.com/62446608/98261156-e853e380-1f62-11eb-9614-871ee213a903.png)

Netlfix Windows
![image](https://user-images.githubusercontent.com/62446608/98261329-1afddc00-1f63-11eb-87f3-10d0f1fcabc4.png)

Windows versión:
![image](https://user-images.githubusercontent.com/62446608/98261329-1afddc00-1f63-11eb-87f3-10d0f1fcabc4.png)

**Comment by lkmvip** [comment]
you edge version?

**Comment by 5J2J** [comment]
> you edge version?

![image](https://user-images.githubusercontent.com/62446608/98360406-7fbf4200-2008-11eb-8ec8-9b9c3a1c2c39.png)

**Comment by lkmvip** [comment]
Now, the store version of the extension does not support streaming 4K. This is actually caused by Microsoft or Netflix. You can use this https://github.com/lkmvip/netflix-4K-DDplus/issues/11#issuecomment-722080911, If you must use the store version, you may need to wait a long time, maybe 10 days, 20 days, because Microsoft review is very slow

**Comment by 5J2J** [comment]
![image](https://user-images.githubusercontent.com/62446608/98373311-d3885600-201d-11eb-8cea-d888828bbeb8.png)
Do I have to activate any of these options?

**Comment by lkmvip** [comment]
no

**Comment by spreadpositivity3** [comment]
used the https://github.com/lkmvip/netflix-4K-DDplus/archive/master.zip
version, still no 4k only 1920x1080p

**Comment by 5J2J** [comment]
It doesn't work for me in 4k either.

**Comment by Phoenomenal** [comment]
It seems that 4K is fixed as it works without  checking disguised as edge  option  but HDR is broken.  Worked fine just a few days ago in EDGE but now  works only in UWP .

I wonder  are the any way to fix  by edit cadmium playercore settings  or just wait till  it will be eventually fixed....

**Comment by B3nji957** [comment]
> used the https://github.com/lkmvip/netflix-4K-DDplus/archive/master.zip
> version, still no 4k only 1920x1080p
> 
> clicked on all 6 options should I not use one or more?

@spreadpositivity3, you need to enable "Use hardware acceleration when available" for your browser (Microsoft Edge). I had the same issue, but it was fixed after I enabled it.

**Comment by gakowalski** [comment]
> 5J2J , you can simply drop this edited file https://www.mediafire.com/file/l2l1k3cpxdvzh3y/cadmium-playercore-6.0026.371.031.js/file in your netflix-4K-DDplus extension root folder rewriting your cadmium-playercore-6.0026.529.031.js file

Nope, Edge detects that something changed, disables the extension and offers to "repair it" which effectively means it will be uninstalled.

> > Forgive my ignorance, where do I do this?
> 
> https://github.com/lkmvip/netflix-4K-DDplus/archive/master.zip

How to manually install the extension?

**Comment by gakowalski** [comment]
Nevermind, in new Edge versions there is "Developer mode" switch in left-bottom part of edge://extensions/

Still, I haven't got all this to work.
